In [10]:
import tensorflow as tf

In [11]:
import numpy as np

In [12]:
tf.__version__

'2.17.0'

In [13]:
a=tf.constant(10)
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [14]:
b=tf.constant(10.0)
b

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [15]:
d=tf.constant(True)
d

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [16]:
np_array = tf.constant(np.array([1,2,3,4]))
np_array

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [17]:
t_id = tf.constant([1,2,3,4])
t_id

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>